const data ={
    products:[
        {
            _id:'1',
            name: 'flower1',
            category: 'bouquet',
            image:'/images/p-1.jpeg',
            price: 300,
            rating: 4.5,
            numReviews:10,
            description: 'High quality product',
        },
        {
            _id:'2',
            name: 'flower2',
            category: 'bouquet',
            image:'/images/p-2.jpeg',
            price: 300,
            rating: 4.5,
            numReviews:10,
            description: 'High quality product',
        },
        {
            _id:'3',
            name: 'flower3',
            category: 'bouquet',
            image:'/images/p-3.jpeg',
            price: 300,
            rating: 4.5,
            numReviews:10,
            description: 'High quality product',
        },
        {
            _id:'4',
            name: 'flower4',
            category: 'bouquet',
            image:'/images/p-4.jpeg',
            price: 300,
            rating: 4.5,
            numReviews:10,
            description: 'High quality product',
        },
        {
            _id:'5',
            name: 'flower5',
            category: 'bouquet',
            image:'/images/p-5.jpeg',
            price: 300,
            rating: 4.5,
            numReviews:10,
            description: 'High quality product',
        },
        {
            _id:'6',
            name: 'flower6',
            category: 'bouquet',
            image:'/images/p-6.jpeg',
            price: 300,
            rating: 4.5,
            numReviews:10,
            description: 'High quality product',
        },
    ]
}
export default data;