const data ={
    products:[
        {
            _id:'1',
            name: 'Flowers1',
            category: 'bouquet',
            image:'/images/p-1.jpeg',
            price: 300,
            countInStock: 10,
            rating: 4.5,
            numReviews:10,
            description: 'High quality product',
        },
        {
            _id:'2',
            name: 'Flowers2',
            category: 'bouquet',
            image:'/images/p-2.jpeg',
            price: 300,
            countInStock:7,
            rating: 2.5,
            numReviews:10,
            description: 'High quality product',
        },
        {
            _id:'3',
            name: 'Flowers3',
            category: 'bouquet',
            image:'/images/p-3.jpeg',
            price: 300,
            countInStock:12,
            rating: 5,
            numReviews:10,
            description: 'High quality product',
        },
        {
            _id:'4',
            name: 'Flowers4',
            category: 'bouquet',
            image:'/images/p-4.jpeg',
            price: 300,
            countInStock:5,
            rating: 4.5,
            numReviews:10,
            description: 'High quality product',
        },
        {
            _id:'5',
            name: 'Flowers5',
            category: 'bouquet',
            image:'/images/p-5.jpeg',
            price: 300,
            countInStock:0,
            rating: 4,
            numReviews:10,
            description: 'High quality product',
        },
        {
            _id:'6',
            name: 'Flowers6',
            category: 'bouquet',
            image:'/images/p-6.jpeg',
            price: 300,
            countInStock:1,
            rating: 4.5,
            numReviews:10,
            description: 'High quality product',
        },
    ]
}
export default data;